version: '3.7'

services: 
  api:
    image: eassbhhtgu/homeapi:latest
    entrypoint: bash -c "/usr/sbin/update-ca-certificates && dotnet HomeApi.WebApplication.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: "443"
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /run/secrets/localhost.key
      ASPNETCORE_Kestrel__Certificates__Default__Path: /run/secrets/localhost.crt
      ASPNETCORE_URLS: https://+
      DeviceAliases:amp-plug: 003192e1a68b
      DeviceAliases:irblaster: 000c1e059cad
      GlobalCache:BroadcastIPAddress: 239.255.250.250
      GlobalCache:BroadcastPort: "4998"
      GlobalCache:ReceivePort: "9131"
      Identity:Authority: https://identityserver
      Identity:ClientId: elgatoapi
      Identity:ClientSecret: 8556e52c6ab90d042bb83b3f0c8894498beeb65cf908f519a2152aceb131d3ee
      Identity:Scope: networkdiscovery
      InfraredAliases:amp-on: "sendir,1:1,3,40192,3,1,96,24,48,24,24,24,48,24,24,24,48,24,24,24,24,24,24,24,24,24,24,24,24,24,48,24,48,24,24,24,24,4000\r"
      InfraredAliases:spdif-switch-one: "sendir,1:2,14,37996,1,1,343,168,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,63,21,63,21,63,21,63,21,63,21,63,21,63,21,63,21,21,21,21,21,21,21,21,21,21,21,21,21,63,21,21,21,63,21,63,21,63,21,63,21,63,21,63,21,21,21,63,21,1512,343,84,21,4858\r"
      InfraredAliases:spdif-switch-two: "sendir,1:2,14,37996,1,1,343,168,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,63,21,63,21,63,21,63,21,63,21,63,21,63,21,63,21,63,21,63,21,63,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,63,21,63,21,63,21,63,21,63,21,1512,343,84,21,4858\r"
      TPLink:Port: "9999"
    ports:
    - 443:443/tcp
    secrets:
    - source: localhost.crt
    - source: localhost.key
    - source: ca.crt
      target: /usr/local/share/ca-certificates/ca.crt

secrets:
  id_rsa:
    file: ${USERPROFILE}\.ssh\id_rsa
  ca.crt:
    file: ${USERPROFILE}\.aspnet\https\ca.crt
  localhost.crt:
    file: ${USERPROFILE}\.aspnet\https\home.crt
  localhost.key:
    file: ${USERPROFILE}\.aspnet\https\home.key
